#ARCH = i386
#ARCH = amd64

all: prog limpa

prog: main.o prompt.o
	gcc -g -Wall main.o -o prog
	./prog
	
#	test: main.c main_test.c
#	gcc -I ./CUnit -L ./CUnit main_test.c -lcunit_$(ARCH) -o test
#	./test

main.o: main.c
	gcc -c -g -Wall main.c
	
prompt.o: ./cadastro/prompt.c
	gcc -c -g -Wall ./cadastro/prompt.c
	
#	gcov: main.c main_test.c
#	gcc -Wall -ftest-coverage -fprofile-args -I ./Cunit -L ./CUnit main_test.c -lcunit_$(ARCH) -o test_gcov
#	./test_gcov
	
limpa: 
	rm *.o 
#	rm *.gcda *.gcno *gcov
